import { HEARTH_TIME_ZONE } from './date-utils.js';
import { MOOD_OPTIONS, moodLabel } from './moods.js';
import { configuredPartners, formatPartnerList } from './partners.js';

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, character => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[character]);
}

function inlineJson(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026');
}

export function getRedesignedDashboardHTML(config) {
  const partners = configuredPartners(config);
  const partnerOptions = partners.map(partner => {
    const escapedPartner = escapeHtml(partner);
    return `<option value="${escapedPartner}">${escapedPartner}</option>`;
  }).join('');
  const hearthOwners = escapeHtml(formatPartnerList(partners));
  const moodOptions = MOOD_OPTIONS.map(mood => `<option value="${escapeHtml(mood)}">${escapeHtml(moodLabel(mood))}</option>`).join('');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Hearth</title>
  <style>
    :root{--bg:#F7F2EA;--card:#FFFDFC;--rose:#B86B7A;--plum:#7C5A72;--gold:#C7A35A;--sage:#8FA58D;--text:#3A3436;--muted:#7D7477;--line:#E8DDD2;--danger:#A44E57;--shadow:0 10px 30px rgba(74,55,59,.08)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.5 system-ui,-apple-system,"Segoe UI",sans-serif}button,input,select,textarea{font:inherit}button{cursor:pointer}
    .shell{width:min(1220px,100%);margin:auto;padding:1.25rem}.topbar{display:flex;align-items:center;gap:1rem;justify-content:space-between;padding:1rem 0 1.2rem;flex-wrap:wrap}.brand{font-family:Georgia,serif;font-size:2rem;color:var(--plum);letter-spacing:.02em}.tagline{color:var(--muted);font-size:.86rem;overflow-wrap:anywhere}
    .menu-toggle{display:none;border:1px solid var(--line);background:var(--card);border-radius:12px;padding:.65rem .85rem;color:var(--plum)}nav{display:flex;gap:.35rem;flex-wrap:wrap;border-block:1px solid var(--line);padding:.75rem 0;margin-bottom:1.5rem}nav a{color:var(--muted);text-decoration:none;padding:.55rem .72rem;border-radius:999px;font-size:.91rem}nav a:hover,nav a.active{color:#fff;background:var(--plum)}
    .page{display:none}.page.active{display:block}.page-head{margin-bottom:1.2rem}.page-head h1{font:700 1.7rem/1.2 Georgia,serif;color:var(--plum);margin:.1rem 0}.page-head p{margin:.35rem 0;color:var(--muted)}.dashboard-date{font-size:.9rem;font-weight:650;color:var(--plum)}
    .grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:1rem}.card{grid-column:span 4;background:var(--card);border:1px solid var(--line);border-radius:18px;padding:1.1rem;box-shadow:var(--shadow);min-width:0}.card.wide{grid-column:span 8}.card.full{grid-column:1/-1}.card.half{grid-column:span 6}.card h2,.card h3{margin:0 0 .8rem;color:var(--plum)}.card h2{font-size:.78rem;text-transform:uppercase;letter-spacing:.11em}.card h3{font-size:1.05rem}.metric{font:700 1.55rem/1.2 Georgia,serif;color:var(--rose)}.muted,.empty{color:var(--muted)}.empty{font-style:italic}.stack{display:grid;gap:.65rem}.row{display:flex;align-items:center;justify-content:space-between;gap:.75rem;padding:.65rem 0;border-bottom:1px solid var(--line)}.row:last-child{border:0}.row-main{min-width:0}.row-title{font-weight:700;overflow-wrap:anywhere}.meta{font-size:.82rem;color:var(--muted)}.badge{display:inline-flex;border-radius:999px;padding:.15rem .52rem;background:#F2E7EA;color:var(--rose);font-size:.73rem;font-weight:700}.badge.sage{background:#E9EFE8;color:#586E56}.badge.gold{background:#F4ECD9;color:#806727}
    form{display:grid;gap:.72rem}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.72rem}.span-2{grid-column:1/-1}label{display:grid;gap:.28rem;color:var(--muted);font-size:.8rem;font-weight:650}input,select,textarea{width:100%;border:1px solid #D9CCC1;border-radius:11px;background:#fff;color:var(--text);padding:.7rem .75rem}textarea{min-height:78px;resize:vertical}input:focus,select:focus,textarea:focus{outline:3px solid rgba(184,107,122,.17);border-color:var(--rose)}.check{display:flex;align-items:center;gap:.5rem}.check input{width:auto}
    .btn{border:0;border-radius:11px;background:var(--rose);color:#fff;padding:.68rem .9rem;font-weight:700}.btn:hover{filter:brightness(.96)}.btn.secondary{background:var(--sage)}.btn.ghost{background:transparent;color:var(--plum);border:1px solid var(--line)}.btn.small{padding:.38rem .58rem;font-size:.78rem}.actions{display:flex;gap:.45rem;flex-wrap:wrap}.notice{min-height:1.4rem;color:var(--sage);font-size:.82rem}.danger{color:var(--danger)}
    .day-grid{display:grid;grid-template-columns:repeat(7,minmax(130px,1fr));gap:.7rem;overflow-x:auto;padding-bottom:.35rem}.day{border:1px solid var(--line);border-radius:14px;padding:.8rem;background:#fff}.day strong{display:block;color:var(--plum)}.subnav{display:flex;gap:.4rem;flex-wrap:wrap;margin:.5rem 0 1rem}.subnav a{font-size:.82rem;color:var(--plum);text-decoration:none;background:#F1E7EC;padding:.35rem .65rem;border-radius:999px}.progress{height:8px;background:#EEE5DD;border-radius:99px;overflow:hidden;margin:.45rem 0}.progress span{display:block;height:100%;background:var(--sage)}
    .shop-item{display:grid;grid-template-columns:auto 1fr auto auto;align-items:center;gap:.55rem}.shop-item.done .row-title{text-decoration:line-through;color:var(--muted)}.shop-item input{width:auto}.meal-photo{width:72px;height:72px;object-fit:cover;border-radius:12px;border:1px solid var(--line)}.section-divider{margin:1.1rem 0 .35rem;padding-top:.9rem;border-top:1px solid var(--line);font-size:.76rem;text-transform:uppercase;letter-spacing:.09em;color:var(--muted)}
    footer{color:var(--muted);text-align:center;font-size:.78rem;padding:2.5rem 0 1rem}
    @media(max-width:900px){.card,.card.wide{grid-column:span 6}.card.full{grid-column:1/-1}.day-grid{grid-template-columns:repeat(7,150px)}}
    @media(max-width:650px){.shell{padding:.85rem}.topbar{align-items:flex-start}.menu-toggle{display:block}nav{display:none;flex-direction:column;align-items:stretch}nav.open{display:flex}nav a{border-radius:10px}.card,.card.wide,.card.half{grid-column:1/-1}.form-grid{grid-template-columns:1fr}.span-2{grid-column:auto}.grid{gap:.8rem}.card{padding:1rem}.brand{font-size:1.7rem}.row{align-items:flex-start}.actions{justify-content:flex-start}}
  </style>
</head>
<body>
<div class="shell">
  <header class="topbar"><div><div class="brand">Hearth</div><div class="tagline">A shared Hearth for ${hearthOwners}</div></div><button class="menu-toggle" id="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button></header>
  <nav id="main-nav" aria-label="Main navigation">
    ${['Dashboard','Moods','Notes','Moments','Dates','Shopping','Medical','Household','Home Admin','Food'].map(label => `<a href="#${label.toLowerCase().replace(' ','-')}" data-page="${label.toLowerCase().replace(' ','-')}">${label}</a>`).join('')}
    <a href="/logout">Log out</a>
  </nav>

  <main>
    <section class="page" id="dashboard"><div class="page-head"><h1>What do I need to know today?</h1><p id="dashboard-date" class="dashboard-date"></p><p>A calm summary of the things that matter now.</p></div><div class="grid">
      <article class="card"><h2>Today</h2><div id="dash-today" class="stack"><p class="empty">Loading…</p></div></article>
      <article class="card"><h2>Mood</h2><div id="dash-mood"></div></article>
      <article class="card"><h2>Next medical appointment</h2><div id="dash-medical"></div></article>
      <article class="card"><h2>Medication today</h2><div id="dash-medication"></div></article>
      <article class="card"><h2>Prescription renewals</h2><div id="dash-prescriptions"></div></article>
      <article class="card"><h2>Household</h2><div id="dash-household"></div></article>
      <article class="card"><h2>Upcoming</h2><div id="dash-upcoming"></div></article>
      <article class="card"><h2>Shopping</h2><div id="dash-shopping"></div></article>
      <article class="card"><h2>Latest</h2><div id="dash-latest"></div></article>
      <article class="card"><h2>Tonight's meal</h2><div id="dash-meal"></div></article>
      <article class="card wide"><h2>Quick capture</h2><form id="quick-form"><label>Put it somewhere safe<input name="content" maxlength="4000" required placeholder="Remember to…"></label><button class="btn" type="submit">Save to Notes</button><div class="notice"></div></form></article>
    </div></section>

    <section class="page" id="moods"><div class="page-head"><h1>Moods</h1><p>A simple check-in, without judgement.</p></div><div class="grid"><article class="card half"><h2>Check in</h2><form id="mood-form"><label>Person<select name="partner">${partnerOptions}</select></label><label>Mood<select name="mood">${moodOptions}</select></label><label>Overall scale (optional)<select name="overall_scale"><option value="">No scale</option><option value="1">1/5</option><option value="2">2/5</option><option value="3">3/5</option><option value="4">4/5</option><option value="5">5/5</option></select></label><label>Note<textarea name="note" maxlength="2000"></textarea></label><button class="btn">Save mood</button></form></article><article class="card half"><h2>Recent moods</h2><div id="mood-list" class="stack"></div></article></div></section>

    <section class="page" id="notes"><div class="page-head"><h1>Notes</h1><p>Shared thoughts and captured reminders.</p></div><div class="grid"><article class="card half"><h2>Leave a note</h2><form id="note-form"><label>From<select name="from">${partnerOptions}</select></label><label>Note<textarea name="content" maxlength="4000" required></textarea></label><button class="btn">Save note</button></form></article><article class="card half"><h2>Recent notes</h2><div id="note-list" class="stack"></div></article></div></section>

    <section class="page" id="moments"><div class="page-head"><h1>Moments</h1><p>The small pieces worth remembering.</p></div><div class="grid"><article class="card half"><h2>Add a moment</h2><form id="moment-form"><label>Date<input type="date" name="date" required></label><label>Title<input name="title" maxlength="200" required></label><label>Description<textarea name="description" maxlength="4000"></textarea></label><button class="btn">Save moment</button></form></article><article class="card half"><h2>Timeline</h2><div id="moment-list" class="stack"></div></article></div></section>

    <section class="page" id="dates"><div class="page-head"><h1>Dates</h1><p>Important days, kept close.</p></div><div class="grid"><article class="card half"><h2>Add a date</h2><form id="date-form"><label>Date<input type="date" name="date" required></label><label>Title<input name="title" maxlength="200" required></label><label class="check"><input type="checkbox" name="recurring"> Repeats yearly</label><button class="btn">Save date</button></form></article><article class="card half"><h2>Upcoming</h2><div id="date-list" class="stack"></div></article></div></section>

    <section class="page" id="shopping"><div class="page-head"><h1>Shopping</h1><p>One list, shared everywhere.</p></div><div class="grid"><article class="card half"><h2>Add an item</h2><form id="shopping-form"><label>Item<input name="item" maxlength="300" required></label><div class="form-grid"><label>Category<input name="category" maxlength="100" value="Other"></label><label>Added by<select name="added_by">${partnerOptions}</select></label></div><button class="btn">Add to list</button></form></article><article class="card half"><h2>Shopping list</h2><div id="shopping-list" class="stack"></div><button id="clear-shopping" class="btn ghost small" type="button">Clear checked</button></article></div></section>

    <section class="page" id="medical"><div class="page-head"><h1>Medical</h1><p>Practical organisation for Crimson and Conrad—not a diagnostic record.</p></div><div class="subnav"><a href="#medical-appointments">Appointments</a><a href="#medical-medications">Medications</a><a href="#medical-doses">Taken today</a><a href="#medical-prescriptions">Prescriptions</a></div><div class="grid">
      <article class="card full" id="medical-appointments"><h2>Appointments</h2><div class="grid"><div class="card half"><form id="appointment-form"><input type="hidden" name="id"><div class="form-grid"><label>Person<select name="person"><option>Crimson</option><option>Conrad</option></select></label><label>Date<input type="date" name="appointment_date" required></label><label>Time<input type="time" name="appointment_time"></label><label>Status<select name="status"><option>Upcoming</option><option>Completed</option><option>Cancelled</option><option>Rescheduled</option></select></label><label>Location<input name="location" maxlength="300"></label><label>Clinic / hospital / GP<input name="clinic" maxlength="300"></label><label>Department or clinician<input name="clinician" maxlength="300"></label><label>Reason / type<input name="reason" maxlength="500" required></label><label class="span-2">Preparation<textarea name="preparation_needed" maxlength="1000"></textarea></label><label class="span-2">Notes<textarea name="notes" maxlength="4000"></textarea></label><label class="check span-2"><input type="checkbox" name="transport_needed"> Transport needed</label></div><div class="actions"><button class="btn">Save appointment</button><button type="button" class="btn ghost" data-reset="appointment-form">Clear</button></div></form></div><div class="card half"><div id="appointment-list" class="stack"></div></div></div></article>
      <article class="card full" id="medical-medications"><h2>Medications</h2><div class="grid"><div class="card half"><form id="medication-form"><input type="hidden" name="id"><div class="form-grid"><label>Person<select name="person"><option>Crimson</option><option>Conrad</option></select></label><label>Medication<input name="name" maxlength="300" required></label><label>Strength<input name="strength" maxlength="100"></label><label>Dose<input name="dose" maxlength="200" required></label><label>Frequency<input name="frequency" maxlength="200" required></label><label>Scheduled times<input name="scheduled_times" placeholder="08:00, 20:00"></label><label>Start date<input type="date" name="start_date" required></label><label>Prescribing source<input name="prescribing_source" maxlength="300"></label><label class="span-2">Notes<textarea name="notes" maxlength="4000"></textarea></label></div><div class="actions"><button class="btn">Save medication</button><button type="button" class="btn ghost" data-reset="medication-form">Clear</button></div></form></div><div class="card half"><h3>Active medications</h3><div id="active-medication-list" class="stack"></div><h3 class="section-divider">Stopped medications</h3><div id="stopped-medication-list" class="stack"></div></div></div></article>
      <article class="card half" id="medical-doses"><h2>Taken today</h2><div id="dose-today" class="stack"></div></article><article class="card half"><h2>Dose history</h2><div id="dose-history" class="stack"></div></article>
      <article class="card full" id="medical-prescriptions"><h2>Prescription renewals</h2><div class="grid"><div class="card half"><form id="prescription-form"><input type="hidden" name="id"><input type="hidden" name="medication_id"><input type="hidden" name="medication_name"><div class="form-grid"><label>Person<select name="person"><option>Crimson</option><option>Conrad</option></select></label><label>Medication<select name="medication_selection" required></select></label><label>Last ordered<input type="date" name="last_ordered_date"></label><label>Next order / renewal<input type="date" name="next_order_date"></label><label>Quantity / days left<input type="number" min="0" name="quantity_remaining"></label><label>Status<select name="status"><option>Enough</option><option>Order soon</option><option>Ordered</option><option>Ready</option><option>Collected</option></select></label><label class="span-2">Notes<textarea name="notes" maxlength="4000" placeholder="For Custom / other, put the item or details here"></textarea></label></div><div class="actions"><button class="btn">Save prescription</button><button type="button" class="btn ghost" data-reset="prescription-form">Clear</button></div></form></div><div class="card half"><div id="prescription-list" class="stack"></div></div></div></article>
    </div></section>

    <section class="page" id="household"><div class="page-head"><h1>Household</h1><p>Just the chores that need doing—no assignees, no project management.</p></div><div class="grid"><article class="card half"><h2>Add a chore</h2><form id="chore-form"><label>Task<input name="task" maxlength="300" required></label><div class="form-grid"><label>Frequency<select name="frequency"><option>One-off</option><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Custom</option></select></label><label>Next due<input type="date" name="next_due_date" required></label><label>Custom days<input type="number" min="1" max="3650" name="recurrence_days"></label></div><label>Notes<textarea name="notes" maxlength="4000"></textarea></label><button class="btn">Save chore</button></form></article><article class="card half"><h2>Chores</h2><div class="subnav"><button type="button" class="btn ghost small" data-chore-filter="today">Today</button><button type="button" class="btn ghost small" data-chore-filter="week">This week</button><button type="button" class="btn ghost small" data-chore-filter="recurring">Recurring</button><button type="button" class="btn ghost small" data-chore-filter="one-off">One-off</button><button type="button" class="btn ghost small" data-chore-filter="completed">Completed</button></div><div id="chore-list" class="stack"></div></article></div></section>

    <section class="page" id="home-admin"><div class="page-head"><h1>Home Admin</h1><p>Renewals, bills, calls and deadlines in one quiet place.</p></div><div class="grid"><article class="card half"><h2>Add an item</h2><form id="admin-form"><input type="hidden" name="id"><label>Title<input name="title" maxlength="300" required></label><div class="form-grid"><label>Category<input name="category" maxlength="100" value="General"></label><label>Due date<input type="date" name="due_date" required></label><label>Recurrence<select name="recurrence"><option>None</option><option>Monthly</option><option>Yearly</option><option>Custom</option></select></label><label>Custom days<input type="number" min="1" max="3650" name="recurrence_days"></label><label>Status<select name="status"><option>Upcoming</option><option>Due soon</option><option>Done</option></select></label></div><label>Notes<textarea name="notes" maxlength="4000"></textarea></label><div class="actions"><button class="btn">Save item</button><button type="button" class="btn ghost" data-reset="admin-form">Clear</button></div></form></article><article class="card half"><h2>Deadlines</h2><div id="admin-list" class="stack"></div></article></div></section>

    <section class="page" id="food"><div class="page-head"><h1>Food</h1><p>Tonight’s plan and the diary you already use.</p></div><div class="subnav"><a href="#meal-planner">Meal planner</a><a href="#food-diary">Meals</a><a href="#saved-meals-card">Favourites</a></div><div class="grid">
      <article class="card full" id="meal-planner"><h2>Seven-day meal planner</h2><form id="meal-plan-form"><div class="form-grid"><label>Date<input type="date" name="plan_date" required></label><label>Meal / dinner<input name="meal" maxlength="300" required></label><label>Notes<input name="notes" maxlength="2000"></label><label>Ingredients needed<input name="ingredients_needed" maxlength="2000" placeholder="cheese, tomatoes"></label></div><button class="btn">Save plan</button></form><div id="meal-plan-list" class="day-grid" style="margin-top:1rem"></div></article>
      <article class="card half" id="saved-meals-card"><h2>Favourite meals</h2><form id="saved-meal-form"><label>Name<input name="name" maxlength="300" required></label><label>Notes<input name="notes" maxlength="2000"></label><label>Ingredients<input name="ingredients" maxlength="2000"></label><button class="btn">Save favourite</button></form><div id="saved-meal-list" class="stack" style="margin-top:1rem"></div></article>
      <article class="card half" id="food-diary"><h2>Log a meal</h2><form id="food-form"><div class="form-grid"><label>Meal<select name="meal_type"><option>breakfast</option><option>lunch</option><option>dinner</option><option>snack</option></select></label><label>Time<input type="time" name="time"></label></div><label>Note<textarea name="note" maxlength="4000"></textarea></label><label>Photo<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label><button class="btn">Add meal</button></form><div id="food-list" class="stack" style="margin-top:1rem"></div></article>
      <article class="card half"><h2>Water</h2><div class="metric" id="water-total">0 ml</div><div class="actions"><button class="btn secondary" data-water="250">+250 ml</button><button class="btn secondary" data-water="500">+500 ml</button></div></article>
      <article class="card half"><h2>Food review</h2><form id="review-form"><label>Date<input type="date" name="date" required></label><label>Reviewer<input name="reviewer" maxlength="80" value="AI"></label><label>Review<textarea name="review" maxlength="6000" required></textarea></label><button class="btn">Save review</button></form><div id="review-list" class="stack" style="margin-top:1rem"></div></article>
    </div></section>
  </main>
  <footer>Hearth · private, practical, and yours · 1.1.4-crimson.4</footer>
</div>
<script>
  const PARTNERS=${inlineJson(partners)};
  const TIME_ZONE=${inlineJson(HEARTH_TIME_ZONE)};
  const MOOD_LABELS=${inlineJson(Object.fromEntries(MOOD_OPTIONS.map(mood => [mood, moodLabel(mood)])))};
  const state={appointments:[],medications:[],prescriptions:[],admin:[],mealPlan:[],savedMeals:[],chores:[],choreFilter:'today',editingPrescription:null};
  const $=id=>document.getElementById(id);
  const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const empty=text=>'<p class="empty">'+esc(text)+'</p>';
  const localParts=(instant=new Date())=>Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(instant).filter(part=>part.type!=='literal').map(part=>[part.type,part.value]));
  const today=()=>{const parts=localParts();return parts.year+'-'+parts.month+'-'+parts.day};
  const addDays=(date,days)=>{const value=new Date(date+'T00:00:00Z');value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10)};
  const fmt=date=>date?new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{timeZone:TIME_ZONE,day:'numeric',month:'short',year:'numeric'}):'—';
  const fmtTime=value=>value?fmt(value.slice(0,10))+' at '+value.slice(11,16):'—';
  async function api(path,method='GET',body){const options={method,headers:{}};if(body!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(body)}const response=await fetch('/api'+path,options);const data=await response.json().catch(()=>({error:'Request failed'}));if(!response.ok){const error=new Error(response.status===409?'This record changed elsewhere. Reload the latest data and try again.':data.error||'Request failed');error.status=response.status;throw error}return data}
  function formData(form){const data=Object.fromEntries(new FormData(form));form.querySelectorAll('input[type=checkbox]').forEach(input=>data[input.name]=input.checked);form.querySelectorAll('input[type=number]').forEach(input=>{data[input.name]=input.value===''?null:Number(input.value)});return data}
  function notify(form,message,error=false){let el=form.querySelector('.notice');if(!el){el=document.createElement('div');el.className='notice';form.append(el)}el.textContent=message;el.classList.toggle('danger',error)}
  function bindForm(id,handler){const form=$(id);form.addEventListener('submit',async event=>{event.preventDefault();try{await handler(formData(form),form);notify(form,'Saved');}catch(error){notify(form,error.message,true)}})}
  function resetForm(id){const form=$(id);form.reset();delete form.dataset.revision;['id','revision'].forEach(name=>{const hidden=form.querySelector('input[name='+name+']');if(hidden)hidden.value=''})}
  async function runAction(action,reload){try{await action()}catch(error){alert(error.message);if(error.status===409&&reload)await reload()}}
  document.querySelectorAll('[data-reset]').forEach(button=>button.onclick=()=>{resetForm(button.dataset.reset);if(button.dataset.reset==='prescription-form'){state.editingPrescription=null;setPrescriptionMedicationOptions()}});
  const nav=$('main-nav');$('menu-toggle').onclick=()=>{const open=nav.classList.toggle('open');$('menu-toggle').setAttribute('aria-expanded',String(open))};
  function showPage(name){document.querySelectorAll('.page').forEach(page=>page.classList.toggle('active',page.id===name));document.querySelectorAll('[data-page]').forEach(link=>link.classList.toggle('active',link.dataset.page===name));nav.classList.remove('open');$('menu-toggle').setAttribute('aria-expanded','false')}
  document.querySelectorAll('[data-page]').forEach(link=>link.onclick=()=>showPage(link.dataset.page));
  const initial=(location.hash||'#dashboard').slice(1);showPage($(initial)&&$(initial).classList.contains('page')?initial:'dashboard');

  async function loadDashboard(){
    const data=await api('/dashboard');
    $('dashboard-date').textContent=data.todayLabel||'';
    const mood=Object.entries(data.moods||{}).filter(([,value])=>value).map(([person,value])=>'<div><strong>'+esc(person)+'</strong> · '+esc(MOOD_LABELS[value.mood]||value.mood)+(value.overall_scale?' <span class="badge">'+value.overall_scale+'/5</span>':'')+'</div>').join('');
    $('dash-mood').innerHTML=mood||empty('No mood check-in yet');
    $('dash-medical').innerHTML=data.nextMedical?'<div class="row-title">'+esc(data.nextMedical.person)+' · '+esc(data.nextMedical.reason)+'</div><div class="meta">'+fmt(data.nextMedical.appointment_date)+(data.nextMedical.appointment_time?' at '+esc(data.nextMedical.appointment_time):'')+'</div>':empty('No upcoming appointment');
    const progress=data.medicationProgress||{};
    $('dash-medication').innerHTML=['Crimson','Conrad'].map(person=>{const value=progress[person]||{taken:0,due:0};const percent=value.due?Math.min(100,value.taken/value.due*100):0;return'<div><strong>'+person+'</strong> '+value.taken+'/'+value.due+' taken<div class="progress"><span style="width:'+percent+'%"></span></div></div>'}).join('');
    $('dash-prescriptions').innerHTML=(data.renewals||[]).length?(data.renewals||[]).slice(0,3).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.medication_name)+'</div><div class="meta">'+esc(item.person)+' · '+fmt(item.next_order_date)+'</div></div><span class="badge gold">'+esc(item.status)+'</span></div>').join(''):empty('Nothing needs ordering soon');
    $('dash-household').innerHTML='<div class="metric">'+(data.household?.dueToday||0)+' due today</div><div class="meta">'+(data.household?.overdue||0)+' overdue</div>';
    const dateItems=(data.upcomingDates||[]).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.title)+'</div><div class="meta">'+fmt(item.date)+'</div></div></div>').join('');
    const adminItems=(data.homeAdmin||[]).slice(0,2).map(item=>'<div class="row"><span>'+esc(item.title)+'</span><span class="meta">'+fmt(item.due_date)+'</span></div>').join('');
    $('dash-upcoming').innerHTML=(dateItems||empty('No upcoming dates'))+(adminItems?'<div class="section-divider">Home Admin</div>'+adminItems:'');
    $('dash-shopping').innerHTML='<div class="metric">'+(data.shoppingCount||0)+' items</div>'+((data.shoppingPreview||[]).map(item=>'<div class="meta">'+esc(item.item)+'</div>').join('')||'<div class="meta">List is clear</div>');
    $('dash-latest').innerHTML=data.latest?'<span class="badge">'+esc(data.latest.type)+'</span><div class="row-title">'+esc(data.latest.title)+'</div>':empty('No notes or moments yet');
    $('dash-meal').innerHTML=data.tonightMeal?'<div class="metric">'+esc(data.tonightMeal.meal)+'</div>'+(data.tonightMeal.ingredients_needed?'<div class="meta">Need: '+esc(data.tonightMeal.ingredients_needed)+'</div>':''):empty('Nothing planned yet');
    const todayItems=[];
    if(data.nextMedical&&data.nextMedical.appointment_date===data.today)todayItems.push('Medical appointment');
    if(data.household?.dueToday)todayItems.push(data.household.dueToday+' household task'+(data.household.dueToday===1?'':'s'));
    if(data.tonightMeal)todayItems.push('Dinner: '+data.tonightMeal.meal);
    $('dash-today').innerHTML=todayItems.length?todayItems.map(item=>'<div class="row-title">'+esc(item)+'</div>').join(''):empty('A quiet day so far');
  }
  bindForm('quick-form',async(data,form)=>{await api('/quick-capture','POST',data);form.reset();await Promise.all([loadDashboard(),loadNotes()])});

  async function loadMoods(){const data=await api('/moods');$('mood-list').innerHTML=(data.moods||[]).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.partner)+' · '+esc(MOOD_LABELS[item.mood]||item.mood)+(item.overall_scale?' <span class="badge">Overall '+item.overall_scale+'/5</span>':'')+'</div><div class="meta">'+esc(item.note||'')+'</div></div></div>').join('')||empty('No moods yet')}
  bindForm('mood-form',async(data,form)=>{data.overall_scale=data.overall_scale===''?null:Number(data.overall_scale);await api('/moods','POST',data);form.reset();await Promise.all([loadMoods(),loadDashboard()])});
  async function loadNotes(){const data=await api('/notes');$('note-list').innerHTML=(data.notes||[]).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.content)+'</div><div class="meta">'+esc(item.from_partner)+'</div></div></div>').join('')||empty('No notes yet')}
  bindForm('note-form',async(data,form)=>{await api('/notes','POST',data);form.reset();await Promise.all([loadNotes(),loadDashboard()])});
  async function loadMoments(){const data=await api('/moments');$('moment-list').innerHTML=(data.moments||[]).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.title)+'</div><div class="meta">'+fmt(item.date)+' · '+esc(item.description||'')+'</div></div></div>').join('')||empty('No moments yet')}
  bindForm('moment-form',async(data,form)=>{await api('/moments','POST',data);form.reset();await Promise.all([loadMoments(),loadDashboard()])});
  async function loadDates(){const data=await api('/dates');$('date-list').innerHTML=(data.dates||[]).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.title)+'</div><div class="meta">'+fmt(item.date)+(item.recurring?' · yearly':'')+'</div></div><button class="btn ghost small" data-delete-date="'+item.id+'">Remove</button></div>').join('')||empty('No dates yet');document.querySelectorAll('[data-delete-date]').forEach(button=>button.onclick=async()=>{await api('/dates/'+button.dataset.deleteDate,'DELETE');await loadDates()})}
  bindForm('date-form',async(data,form)=>{await api('/dates','POST',data);form.reset();await Promise.all([loadDates(),loadDashboard()])});

  async function loadShopping(){const data=await api('/shopping');$('shopping-list').innerHTML=(data.items||[]).map(item=>'<div class="row shop-item '+(item.checked?'done':'')+'"><input type="checkbox" data-check-shop="'+item.id+'" data-revision="'+item.revision+'" '+(item.checked?'checked':'')+' aria-label="Mark '+esc(item.item)+'"><div><div class="row-title">'+esc(item.item)+'</div><div class="meta">'+esc(item.category)+' · '+esc(item.added_by)+'</div></div><span></span><button class="btn ghost small" data-delete-shop="'+item.id+'">Remove</button></div>').join('')||empty('Nothing on the list');document.querySelectorAll('[data-check-shop]').forEach(input=>input.onchange=()=>runAction(async()=>{await api('/shopping/'+input.dataset.checkShop+'/check','POST',{checked:input.checked,revision:Number(input.dataset.revision)});await Promise.all([loadShopping(),loadDashboard()])},loadShopping));document.querySelectorAll('[data-delete-shop]').forEach(button=>button.onclick=async()=>{await api('/shopping/'+button.dataset.deleteShop,'DELETE');await Promise.all([loadShopping(),loadDashboard()])})}
  bindForm('shopping-form',async(data,form)=>{await api('/shopping','POST',data);form.reset();await Promise.all([loadShopping(),loadDashboard()])});$('clear-shopping').onclick=async()=>{await api('/shopping/checked','DELETE');await loadShopping()};

  function medicationRow(item){const stopped=!item.active&&item.stopped_date?' · stopped '+fmt(item.stopped_date):'';const reason=!item.active&&item.stopped_reason?' · '+esc(item.stopped_reason):'';return'<div class="row"><div class="row-main"><div class="row-title">'+esc(item.person)+' · '+esc(item.name)+' '+esc(item.strength||'')+'</div><div class="meta">'+esc(item.dose)+' · '+esc(item.frequency)+stopped+reason+'</div></div><div class="actions"><button class="btn ghost small" data-edit-medication="'+item.id+'">Edit</button>'+(item.active?'<button class="btn ghost small" data-stop-medication="'+item.id+'">Stop medication</button>':'<button class="btn secondary small" data-reactivate-medication="'+item.id+'">Reactivate</button>')+'</div></div>'}
  async function loadMedical(){
    const [appointments,medications,doses,prescriptions]=await Promise.all([api('/medical/appointments'),api('/medical/medications'),api('/medical/doses'),api('/medical/prescriptions')]);
    state.appointments=appointments.appointments||[];state.medications=medications.medications||[];state.prescriptions=prescriptions.prescriptions||[];
    $('appointment-list').innerHTML=state.appointments.map(item=>'<div class="row"><div class="row-main"><div class="row-title">'+esc(item.person)+' · '+esc(item.reason)+'</div><div class="meta">'+fmt(item.appointment_date)+(item.appointment_time?' at '+esc(item.appointment_time):'')+' · '+esc(item.status)+'</div></div><button class="btn ghost small" data-edit-appointment="'+item.id+'">Edit</button></div>').join('')||empty('No appointments');
    $('active-medication-list').innerHTML=state.medications.filter(item=>item.active).map(medicationRow).join('')||empty('No active medications');
    $('stopped-medication-list').innerHTML=state.medications.filter(item=>!item.active).map(medicationRow).join('')||empty('No stopped medications');
    renderDoseToday(state.medications,doses.doses||[]);
    $('dose-history').innerHTML=(doses.doses||[]).slice(0,30).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.person)+' · '+esc(item.medication_name)+'</div><div class="meta">'+esc(item.status)+' · '+fmtTime(item.scheduled_at)+'</div></div></div>').join('')||empty('No doses logged');
    $('prescription-list').innerHTML=state.prescriptions.map(item=>'<div class="row"><div><div class="row-title">'+esc(item.person)+' · '+esc(item.medication_name)+'</div><div class="meta">'+fmt(item.next_order_date)+' · '+esc(item.status)+'</div></div><button class="btn ghost small" data-edit-prescription="'+item.id+'">Edit</button></div>').join('')||empty('No prescription renewals');
    setPrescriptionMedicationOptions();bindMedicalButtons();
  }
  function renderDoseToday(medications,doses){const day=today();$('dose-today').innerHTML=medications.filter(item=>item.active).flatMap(item=>(item.scheduled_times||[]).map(time=>{const scheduled=day+'T'+time;const log=doses.find(d=>d.medication_id===item.id&&d.scheduled_at.slice(0,16)===scheduled);return'<div class="row"><div><div class="row-title">'+esc(item.person)+' · '+esc(item.name)+'</div><div class="meta">'+esc(time)+' · '+esc(log?.status||'Due')+'</div></div><div class="actions">'+(!log||log.status==='Due'?'<button class="btn secondary small" data-dose="'+item.id+'" data-time="'+scheduled+'" data-status="Taken">Taken</button><button class="btn ghost small" data-dose="'+item.id+'" data-time="'+scheduled+'" data-status="Skipped">Skip</button>':'')+'</div></div>'})).join('')||empty('No scheduled doses today');document.querySelectorAll('[data-dose]').forEach(button=>button.onclick=async()=>{await api('/medical/doses','POST',{medication_id:Number(button.dataset.dose),scheduled_at:button.dataset.time,status:button.dataset.status});await Promise.all([loadMedical(),loadDashboard()])})}
  function fill(form,item,fields){fields.forEach(field=>{const input=form.elements[field];if(field==='revision'&&!input){form.dataset.revision=String(item.revision);return}if(!input)return;if(input.type==='checkbox')input.checked=Boolean(item[field]);else if(field==='scheduled_times')input.value=(item[field]||[]).join(', ');else input.value=item[field]??''})}
  function setPrescriptionMedicationOptions(existing=null){
    const form=$('prescription-form');const select=form.elements.medication_selection;const person=form.elements.person.value;select.replaceChildren();
    const addOption=(value,label)=>{const option=document.createElement('option');option.value=value;option.textContent=label;select.append(option)};
    addOption('all','All medications');addOption('custom','Custom / other');
    state.medications.filter(item=>item.active&&item.person===person).forEach(item=>addOption('medication:'+item.id,item.name+(item.strength?' '+item.strength:'')));
    if(existing?.medication_id){const medication=state.medications.find(item=>item.id===Number(existing.medication_id));if(medication&&!medication.active){addOption('existing:'+medication.id,existing.medication_name+' — inactive')}else if(!medication){addOption('existing:'+existing.medication_id,existing.medication_name+' — existing renewal')}select.value=(medication?.active?'medication:':'existing:')+existing.medication_id}
    else if(existing){if(existing.medication_name==='All medications')select.value='all';else if(existing.medication_name==='Custom / other')select.value='custom';else{addOption('legacy',existing.medication_name+' — existing renewal');select.value='legacy'}}
    syncPrescriptionMedication(existing);
  }
  function syncPrescriptionMedication(existing=null){const form=$('prescription-form');const value=form.elements.medication_selection.value;if(value.startsWith('medication:')||value.startsWith('existing:')){const id=Number(value.split(':')[1]);const medication=state.medications.find(item=>item.id===id);form.elements.medication_id.value=id;form.elements.medication_name.value=value.startsWith('existing:')?(existing?.medication_name||medication?.name||''):medication?.name||''}else{form.elements.medication_id.value='';form.elements.medication_name.value=value==='all'?'All medications':value==='custom'?'Custom / other':existing?.medication_name||''}}
  function editPrescription(item){state.editingPrescription=item;const form=$('prescription-form');fill(form,item,['id','revision','person','last_ordered_date','next_order_date','quantity_remaining','status','notes']);setPrescriptionMedicationOptions(item)}
  function bindMedicalButtons(){document.querySelectorAll('[data-edit-appointment]').forEach(button=>button.onclick=()=>fill($('appointment-form'),state.appointments.find(item=>item.id===Number(button.dataset.editAppointment)),['id','revision','person','appointment_date','appointment_time','status','location','clinic','clinician','reason','preparation_needed','notes','transport_needed']));document.querySelectorAll('[data-edit-medication]').forEach(button=>button.onclick=()=>fill($('medication-form'),state.medications.find(item=>item.id===Number(button.dataset.editMedication)),['id','revision','person','name','strength','dose','frequency','scheduled_times','start_date','prescribing_source','notes']));document.querySelectorAll('[data-stop-medication]').forEach(button=>button.onclick=()=>runAction(async()=>{const item=state.medications.find(value=>value.id===Number(button.dataset.stopMedication));const reason=prompt('Optional reason for stopping this medication:')||'';await api('/medical/medications/'+item.id,'PUT',{...item,active:false,stopped_date:today(),stopped_reason:reason});await Promise.all([loadMedical(),loadDashboard()])},loadMedical));document.querySelectorAll('[data-reactivate-medication]').forEach(button=>button.onclick=()=>runAction(async()=>{const item=state.medications.find(value=>value.id===Number(button.dataset.reactivateMedication));await api('/medical/medications/'+item.id+'/reactivate','POST',{revision:item.revision});await Promise.all([loadMedical(),loadDashboard()])},loadMedical));document.querySelectorAll('[data-edit-prescription]').forEach(button=>button.onclick=()=>editPrescription(state.prescriptions.find(item=>item.id===Number(button.dataset.editPrescription))))}
  bindForm('appointment-form',async(data,form)=>{const id=data.id;delete data.id;if(id)data.revision=Number(form.dataset.revision);await api('/medical/appointments'+(id?'/'+id:''),id?'PUT':'POST',data);resetForm('appointment-form');await Promise.all([loadMedical(),loadDashboard()])});
  bindForm('medication-form',async(data,form)=>{const id=data.id;delete data.id;if(id)data.revision=Number(form.dataset.revision);data.scheduled_times=String(data.scheduled_times||'').split(',').map(value=>value.trim()).filter(Boolean);await api('/medical/medications'+(id?'/'+id:''),id?'PUT':'POST',data);resetForm('medication-form');await Promise.all([loadMedical(),loadDashboard()])});
  bindForm('prescription-form',async(data,form)=>{const id=data.id;delete data.id;if(id)data.revision=Number(form.dataset.revision);delete data.medication_selection;data.medication_id=data.medication_id?Number(data.medication_id):null;await api('/medical/prescriptions'+(id?'/'+id:''),id?'PUT':'POST',data);state.editingPrescription=null;resetForm('prescription-form');setPrescriptionMedicationOptions();await Promise.all([loadMedical(),loadDashboard()])});
  $('prescription-form').elements.person.onchange=()=>{state.editingPrescription=null;setPrescriptionMedicationOptions()};
  $('prescription-form').elements.medication_selection.onchange=()=>syncPrescriptionMedication(state.editingPrescription);

  function renderHousehold(){const day=today();const week=addDays(day,6);const visible=state.chores.filter(item=>state.choreFilter==='today'?!item.done&&item.next_due_date<=day:state.choreFilter==='week'?!item.done&&item.next_due_date<=week:state.choreFilter==='recurring'?!item.done&&item.frequency!=='One-off':state.choreFilter==='one-off'?!item.done&&item.frequency==='One-off':Boolean(item.done));$('chore-list').innerHTML=visible.map(item=>'<div class="row"><div><div class="row-title">'+esc(item.task)+'</div><div class="meta">'+fmt(item.next_due_date)+' · '+esc(item.frequency)+(item.next_due_date<day&&!item.done?' · overdue':'')+'</div></div>'+(item.done?'<span class="badge sage">Done</span>':'<button class="btn secondary small" data-complete-chore="'+item.id+'">Done</button>')+'</div>').join('')||empty('No chores in this view');document.querySelectorAll('[data-complete-chore]').forEach(button=>button.onclick=()=>runAction(async()=>{const item=state.chores.find(value=>value.id===Number(button.dataset.completeChore));await api('/household/'+item.id+'/complete','POST',{revision:item.revision});await Promise.all([loadHousehold(),loadDashboard()])},loadHousehold))}
  async function loadHousehold(){const data=await api('/household');state.chores=data.chores||[];renderHousehold()}
  document.querySelectorAll('[data-chore-filter]').forEach(button=>button.onclick=()=>{state.choreFilter=button.dataset.choreFilter;renderHousehold()});
  bindForm('chore-form',async(data,form)=>{await api('/household','POST',data);form.reset();await Promise.all([loadHousehold(),loadDashboard()])});

  async function loadAdmin(){const data=await api('/home-admin');state.admin=data.items||[];$('admin-list').innerHTML=state.admin.map(item=>'<div class="row"><div><div class="row-title">'+esc(item.title)+'</div><div class="meta">'+esc(item.category)+' · '+fmt(item.due_date)+' · '+esc(item.status)+'</div></div><div class="actions"><button class="btn ghost small" data-edit-admin="'+item.id+'">Edit</button>'+(item.status!=='Done'?'<button class="btn secondary small" data-done-admin="'+item.id+'">Done</button>':'')+'</div></div>').join('')||empty('No admin deadlines');document.querySelectorAll('[data-edit-admin]').forEach(button=>button.onclick=()=>fill($('admin-form'),state.admin.find(item=>item.id===Number(button.dataset.editAdmin)),['id','revision','title','category','due_date','recurrence','recurrence_days','status','notes']));document.querySelectorAll('[data-done-admin]').forEach(button=>button.onclick=()=>runAction(async()=>{const item=state.admin.find(value=>value.id===Number(button.dataset.doneAdmin));await api('/home-admin/'+item.id,'PUT',{...item,status:'Done'});await Promise.all([loadAdmin(),loadDashboard()])},loadAdmin))}
  bindForm('admin-form',async(data,form)=>{const id=data.id;delete data.id;if(id)data.revision=Number(form.dataset.revision);await api('/home-admin'+(id?'/'+id:''),id?'PUT':'POST',data);resetForm('admin-form');await Promise.all([loadAdmin(),loadDashboard()])});

  async function loadFood(){const start=today();const end=addDays(start,6);const [plan,saved,food,water,reviews]=await Promise.all([api('/meal-plan?from='+start+'&to='+end),api('/saved-meals'),api('/food'),api('/water'),api('/food/reviews')]);state.mealPlan=plan.meals||[];state.savedMeals=saved.meals||[];const byDate=Object.fromEntries(state.mealPlan.map(item=>[item.plan_date,item]));$('meal-plan-list').innerHTML=Array.from({length:7},(_,index)=>{const date=addDays(start,index);const item=byDate[date];return'<div class="day"><strong>'+new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{timeZone:TIME_ZONE,weekday:'short',day:'numeric'})+'</strong>'+(item?'<div class="row-title">'+esc(item.meal)+'</div><div class="meta">'+esc(item.notes||'')+'</div>'+(item.ingredients_needed?'<button class="btn ghost small" data-add-ingredients="'+item.id+'">Add ingredients</button>':''): '<div class="empty">Not planned</div>')+'</div>'}).join('');$('saved-meal-list').innerHTML=state.savedMeals.map(item=>'<div class="row"><div><div class="row-title">'+esc(item.name)+'</div><div class="meta">'+esc(item.ingredients||item.notes||'')+'</div></div><button class="btn ghost small" data-use-meal="'+item.id+'">Use</button></div>').join('')||empty('No favourite meals');$('food-list').innerHTML=(food.entries||[]).map(item=>'<div class="row"><div style="display:flex;gap:.7rem;align-items:center">'+(item.photo_key?'<img class="meal-photo" src="/api/food/photo/'+encodeURIComponent(item.photo_key)+'" alt="Meal photo">':'')+'<div><div class="row-title">'+esc(item.meal_type)+' · '+esc(item.time)+'</div><div class="meta">'+esc(item.note||'')+'</div></div></div></div>').join('')||empty('Nothing logged today');$('water-total').textContent=(water.total_ml||0)+' ml';$('review-list').innerHTML=(reviews.reviews||[]).map(item=>'<div class="row"><div><div class="row-title">'+esc(item.date)+' · '+esc(item.reviewer)+'</div><div class="meta">'+esc(item.review)+'</div></div></div>').join('')||empty('No reviews yet');document.querySelectorAll('[data-add-ingredients]').forEach(button=>button.onclick=async()=>{await api('/meal-plan/'+button.dataset.addIngredients+'/add-ingredients','POST');await Promise.all([loadShopping(),loadDashboard()])});document.querySelectorAll('[data-use-meal]').forEach(button=>button.onclick=()=>{const item=state.savedMeals.find(value=>value.id===Number(button.dataset.useMeal));const form=$('meal-plan-form');form.elements.meal.value=item.name;form.elements.notes.value=item.notes||'';form.elements.ingredients_needed.value=item.ingredients||'';form.elements.meal.focus()})}
  bindForm('meal-plan-form',async(data,form)=>{await api('/meal-plan','POST',data);form.reset();await Promise.all([loadFood(),loadDashboard()])});bindForm('saved-meal-form',async(data,form)=>{await api('/saved-meals','POST',data);form.reset();await loadFood()});
  bindForm('food-form',async(data,form)=>{let photo_key=null;const file=form.elements.photo.files[0];if(file){const upload=new FormData();upload.set('photo',file);const response=await fetch('/api/food/photo',{method:'POST',body:upload});const uploaded=await response.json();if(!response.ok)throw new Error(uploaded.error||'Photo upload failed');photo_key=uploaded.key}await api('/food','POST',{meal_type:data.meal_type,time:data.time||undefined,note:data.note||undefined,photo_key});form.reset();await loadFood()});
  document.querySelectorAll('[data-water]').forEach(button=>button.onclick=async()=>{await api('/water','POST',{amount_ml:Number(button.dataset.water)});await loadFood()});bindForm('review-form',async(data,form)=>{await api('/food/reviews','POST',data);form.elements.review.value='';await loadFood()});

  $('moment-form').elements.date.value=today();$('date-form').elements.date.value=today();$('appointment-form').elements.appointment_date.value=today();$('medication-form').elements.start_date.value=today();$('chore-form').elements.next_due_date.value=today();$('admin-form').elements.due_date.value=today();$('meal-plan-form').elements.plan_date.value=today();$('review-form').elements.date.value=today();
  Promise.all([loadDashboard(),loadMoods(),loadNotes(),loadMoments(),loadDates(),loadShopping(),loadMedical(),loadHousehold(),loadAdmin(),loadFood()]).catch(error=>console.error('Hearth load failed',error));
</script>
</body>
</html>`;
}
